### ISSUE TITLE
How to use this plugin to receive the parent span passed from the istio sidecar

### ISSUE THREAD

**Issue by njfanxun** [go-gorm/opentelemetry#13]
I developed a http service using gin framework. The service has an interface to call gorm's framework for database queries. The telemetry of the entire service is generated through istio sidecar and reported to jaeger. Using the plugin alone, it is impossible to associate gorm's telemetry with the http service call.

How to pass the parent span and gorm association generated by istio

**Comment by zstone12** [comment]
@njfanxun The current code indeed cannot achieve this task. You can modify it based on this plugin，extract information from the http.Header.you can refer to (https://github.com/liamhao/istio-gorm-tracing/blob/master/istio-gorm-tracing.go)

**Comment by njfanxun** [comment]
@zstone12 [istio-gorm-tracing.go](https://github.com/liamhao/istio-gorm-tracing/blob/master/istio-gorm-tracing.go)use opentracing sdk,now iwant use opentelemetry sdk. I almost understand the usage of otel sdk。Anyway, thank you！
