### ISSUE TITLE
Is context propagated automatically without using the function WithContext?

### ISSUE THREAD

**Issue by ervitis** [go-gorm/opentelemetry#22]
## Your Question

As other tracing methods like [sqlx](https://github.com/uptrace/opentelemetry-go-extra/tree/main/otelsqlx), it is not necessary to call a function to pass the context as a parameter. But in the examples folder, you call `WithContext` and pass the context there.

I have seen in the [code](https://github.com/go-gorm/opentelemetry/blob/master/tracing/tracing.go#L103) that the tracing plugin is called in the hooks so, do I need to call the method `WithContext` when we want to trace the SQL query?

## The document you expected this should be explained

The README.md should have an example after its initialization.

## Expected answer

Two possibilities:
- Yes you need to use the method `WithContext` every time you want to execute any query
- No, it is not

**Comment by zstone12** [comment]
@ervitis  You don't have to call WithContext for each query execution. Refer to the official document on [Context](https://gorm.io/docs/context.html#Continuous-Session-Mode) for proper usage. Here's a example:
`tx := db.WithContext(ctx)`
`tx.First(&user, 1)`
`tx.Model(&user).Update("role", "admin")`

**Comment by ervitis** [comment]
@zstone12 thank you for the answer. And yes, for a simple example you can do that but it's necessary to call the method `WithContext` to trace the request, right?

**Comment by zstone12** [comment]
> @zstone12 thank you for the answer. And yes, for a simple example you can do that but it's necessary to call the method `WithContext` to trace the request, right?

right.

**Comment by ervitis** [comment]
thank you so much!
