### ISSUE TITLE
404 on https://gorm.io/plugin/opentelemetry?go-get=1

### ISSUE THREAD

**Issue by danieltmartin** [go-gorm/opentelemetry#3]
## Description

Looks like the plugin doesn't exist on gorm.io:

```
go get gorm.io/plugin/opentelemetry
go: unrecognized import path "gorm.io/plugin/opentelemetry": reading https://gorm.io/plugin/opentelemetry?go-get=1: 404 Not Found
```

**Comment by zstone12** [comment]
@danieltmartin solve it in https://github.com/go-gorm/gorm.io/pull/565. Now`go get gorm.io/plugin/opentelemetry
` it works. Thank you for raising the issue.
