### ISSUE TITLE
Metrics not working when PrepareStmt is enabled

### ISSUE THREAD

**Issue by houxul** [go-gorm/opentelemetry#30]
## Description
When using GORM with the PrepareStmt option enabled, the metrics functionality in the gorm.io/plugin/opentelemetry plugin does not work. This results in the inability to collect and monitor performance metrics for database operations.
```
		config := gorm.Config{
                       PrepareStmt:    true,
		}
		db, err := gorm.Open(postgres.Open(dsn), &config)
		if err != nil {
			panic(err)
		}
		db.Use(opentelemetry.NewPlugin())
```

**Comment by zstone12** [comment]
@houxul  Hi,houxui.Please tell us the specific version you are using.

**Comment by houxul** [comment]
@zstone12 hello
commit 5195d480ace081e54e14da55df73174b894cf786 (HEAD -> master, tag: v0.1.7, origin/master, origin/HEAD)

**Comment by zstone12** [comment]
@houxul You mentioned that it doesn't work when PrepareStmt option enabled . Does it work when  PrepareStmt option disabled ?

**Comment by houxul** [comment]
> @houxul You mentioned that it doesn't work when PrepareStmt option enabled . Does it work when PrepareStmt option disabled ? And the code in the `examples/metric/metrics` directory may provide some inspiration for you to use metrics.

It only doesn't work when PrepareStmt is enabled. I use pgsql.

**Comment by zstone12** [comment]
@houxul I think I have probably found the reason. https://github.com/go-gorm/opentelemetry/blob/5195d480ace081e54e14da55df73174b894cf786/tracing/tracing.go#L65 There will be one for db Type determination of `db.ConnPool`. If PrepareStmt is enabled, db will be reset The `db.ConnPool ` field causes the type assertion to fail, resulting in failure to start metrcis function. https://github.com/go-gorm/gorm/blob/deceebfab8c460cfee229233aded2821ac6b08eb/gorm.go#L203

**Comment by zstone12** [comment]
@houxul  fixed. You can use the latest version(v0.1.8).
