### ISSUE TITLE
 Conflict Between gorm-opentelemetry and Soft Delete Plugin Causes SQL Error

### ISSUE THREAD

**Issue by aryabharat** [go-gorm/opentelemetry#34]
#Description:
I'm using the [go-gorm/opentelemetry](https://github.com/go-gorm/opentelemetry) package in my Golang application alongside GORM. My application also utilizes the soft delete plugin provided by GORM. However, when both are used together, I encounter the following error:

```
ERROR: could not determine data type of parameter $3 (SQLSTATE 42P18)
```
Here's the SQL generated:
```
SELECT * FROM "<>" WHERE "<>" = false AND "<>"."deleted_at" = 0 ORDER BY created_at desc LIMIT 10
```

Steps to Reproduce:

Integrate the gorm-opentelemetry package into a GORM-based project.
Add the soft delete plugin to a model.
Perform a query on a table with the soft delete condition.
Expected Behavior:
The query should execute without errors, and OpenTelemetry instrumentation should not conflict with the soft delete plugin.

Actual Behavior:
The query fails with the error:
could not determine data type of parameter $3 (SQLSTATE 42P18).

Environment:

GORM version: gorm.io/gorm v1.25.12
go-gorm/opentelemetry version: gorm.io/plugin/opentelemetry v0.1.10
Database: PostgreSQL
Additional Notes:
It seems there might be a conflict between the soft delete logic and the instrumentation provided by the gorm-opentelemetry package, potentially in how query parameters are handled. Please let me know if additional information or a minimal reproducible example is needed.

Please let me know if i understood it wrongly.

**Comment by aryabharat** [comment]
It's also a occues with gorm-opentelemetry,
when i upgraded version to getting the same error
```
	gorm.io/driver/postgres v1.5.4
	gorm.io/gorm v1.25.12
	gorm.io/plugin/soft_delete v1.2.0
```

**Comment by zstone12** [comment]
@aryabharat I wonder if the problem still exists when you don't use the gorm-opentelemetry plugin.

**Comment by aryabharat** [comment]
@zstone12 yes we are using gorm-opentelemetry plugin only. But have noticed it's issue with the below packages.
```
gorm.io/gorm v1.25.12
gorm.io/plugin/soft_delete v1.2.0
```

I think this is caused by this change in soft_delete: https://github.com/go-gorm/soft_delete/commit/cfff53939c574c6c801c95307aa8c2120af4ed41

**Comment by zstone12** [comment]
@aryabharat So it might have nothing to do with Gorm-OpenTelemetry? If it's a problem with soft_delete, you can open an issue under the soft_delete repository.

> @zstone12 yes we are using gorm-opentelemetry plugin only. But have noticed it's issue with the below packages.
> 
> ```
> gorm.io/gorm v1.25.12
> gorm.io/plugin/soft_delete v1.2.0
> ```
> 
> I think this is caused by this change in soft_delete: [go-gorm/soft_delete@cfff539](https://github.com/go-gorm/soft_delete/commit/cfff53939c574c6c801c95307aa8c2120af4ed41)

**Comment by aryabharat** [comment]
closing as per comment.
