### ISSUE TITLE
Missing logging/logrus 

### ISSUE THREAD

**Issue by jay-youngn** [go-gorm/opentelemetry#35]
## Where is `logging/logrus`

```
go mod tidy

go: finding module for package gorm.io/plugin/opentelemetry/logging/logrus
go: pkg/tracing imports
        gorm.io/plugin/opentelemetry/logging/logrus: module gorm.io/plugin/opentelemetry@latest found (v0.1.10), but does not contain package gorm.io/plugin/opentelemetry/logging/logrus
```

**Comment by jay-youngn** [comment]
#32 
It looks like a new mod has been created.
However package path was incorrect in this project.

When importing `gorm.io/plugin/opentelemetry/tracing` and `gorm.io/plugin/opentelemetry/logging/logrus`,
And upgrade gorm.io/plugin/opentelemetry to v0.1.9 above

Run `go get -u gorm.io/plugin/opentelemetry/logging/logrus`
Will see `...reading https://gorm.io/plugin/opentelemetry/logging/logrus?go-get=1: 404 Not Found...`

**Comment by zstone12** [comment]
@jay-youngn Thank you for your feedback, I am trying to fix it.
